- hosts: localhost # use all for remote
  vars:
    extensions:
      - dendron-markdown-links
      - dendron-markdown-notes
  tasks:
    - name: copy script
      copy:
        src: "../scripts/publish.sh"
        dest: "../../{{ item }}/scripts/publish.sh"
        mode: "0711"
      loop: "{{ extensions }}"
